RemainBullet: 450
RemainTime: 270
Hp: 200
HomeHp: 200
TimeOff: 1

ConnectMaxTimes: 5
ConnectWaitOnceSecond: 5


Debug:
  enable: false
  hp: true
  mode: true
  remain_time: true
  remain_exchange_times: true
  remain_bullet: true
  damage_reduction: true
  is_our_outpost_break: true
  is_enemy_outpost_break: true
  game_start: true
  is_fort_occupy: true




HomePoint:
  x: 0.3003413677215576
  y: 0.05908632278442383
PatrolPointA:
  x: 4.765523433685303
  y: 1.2500563859939575
PatrolPointB:
  x: 6.294489860534668
  y: -1.1023938655853271
TargetDoorPoint:
  x: 2.5
  y: 5.5
CenterPoint:
  x: 2.5
  y: 5.5