small_gicp_relocalization:
  ros__parameters:
    use_sim_time: True
    num_threads: 4
    num_neighbors: 10
    global_leaf_size: 0.25
    registered_leaf_size: 0.25
    max_dist_sq: 1.0
    map_frame: "map"
    odom_frame: "odom"
    base_frame: "base_link"
    lidar_frame: "lidar_odom"
