BaudSpeed: 460800
Databits: 8
Stopbits: 1
Parity: 78



SendSetting:
  Ids: [0]
  0:
    Head: 0x7c
    Tail: 0xc7
  1:
    Head: 0x6b
    Tail: 0xb6
  2:
    Head: 0x7c
    Tail: 0xc7
ReceiveSetting:
  Ids: [0]
  0:
    Head: 0x7c
    Tail: 0xc7
    Check:
      Head: false
      Tail: false
      Crc: false
  1:
    Head: 0x6b
    Tail: 0xb6
    Check:
      Head: false
      Tail: false
      Crc: false
  2:
    Head: 0x7c
    Tail: 0xc7
    Check:
      Head: true
      Tail: true
      Crc: true
